name: dimsummaster
description: 'A new Flutter project.'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  charset_converter: ^2.1.1
  cloud_firestore: ^4.13.2
  equatable: ^2.0.5
  esc_pos_bluetooth: ^0.4.1
  esc_pos_utils: ^1.1.0
  esc_pos_utils_plus: ^2.0.1+6
  firebase: ^9.0.3
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.4
  google_fonts: ^4.0.4
  intl: ^0.18.1
  provider: ^6.1.1
  rename: ^3.0.1
  rxdart: ^0.26.0
  sunmi_printer_plus: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# dependency_overrides:
#   rxdart: ^0.27.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
