// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS7u4zWcjPWCsB-hBMNypysLSYvMakpyg',
    appId: '1:899636508246:web:e8a300315ffad9f1e1adf7',
    messagingSenderId: '899636508246',
    projectId: 'dimsummasterpos',
    authDomain: 'dimsummasterpos.firebaseapp.com',
    storageBucket: 'dimsummasterpos.appspot.com',
    measurementId: 'G-JP7S6P1C02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa-MVPt_qBaRXLB3Vi9DqGZ6HzglVODBU',
    appId: '1:899636508246:android:5ad832ebaf7ff349e1adf7',
    messagingSenderId: '899636508246',
    projectId: 'dimsummasterpos',
    storageBucket: 'dimsummasterpos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWLxatugENSNDC2mKvg3RUu8p1Q0moY1k',
    appId: '1:899636508246:ios:913c9282f5265a54e1adf7',
    messagingSenderId: '899636508246',
    projectId: 'dimsummasterpos',
    storageBucket: 'dimsummasterpos.appspot.com',
    iosBundleId: 'com.supakornemch.dimsummaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWLxatugENSNDC2mKvg3RUu8p1Q0moY1k',
    appId: '1:899636508246:ios:faf41b20a86975f1e1adf7',
    messagingSenderId: '899636508246',
    projectId: 'dimsummasterpos',
    storageBucket: 'dimsummasterpos.appspot.com',
    iosBundleId: 'com.example.dimsummaster.RunnerTests',
  );
}
